@baseUrl = http://localhost:3000/api
@token =

### Signup a user
POST {{baseUrl}}/auth/signup
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "s3cret123"
}

###

### Login and save token
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "s3cret123"
}

###

@token = {{login.response.body.token}}


### Create a new ticket
POST {{baseUrl}}/tickets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Cannot log in",
  "description": "User gets error when trying to log in.",
  "createdBy": "user@example.com"
}


### Get all tickets
GET {{baseUrl}}/tickets
Authorization: Bearer {{token}}

### Create a new ticket
POST {{baseUrl}}/tickets
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Cannot log in",
  "description": "User gets error when trying to log in.",
  "createdBy": "user@example.com"
}

### Get a ticket by ID
GET {{baseUrl}}/tickets/687967da6c97c33526f1f80b
Authorization: Bearer {{token}}

### Update a ticket by ID
PUT {{baseUrl}}/tickets/687967da6c97c33526f1f80b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Cannot log in - Updated",
  "description": "User gets error when trying to log in - Updated.",
  "createdBy": "user@example.com"
}

### Delete a ticket by ID
DELETE {{baseUrl}}/tickets/68790e1e5a8c8ebb843f34dc
Authorization: Bearer {{token}}

### Patch ticket status only
PATCH {{baseUrl}}/tickets/687967da6c97c33526f1f80b
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "status": "in progress"
}

### Patch multiple fields
PATCH {{baseUrl}}/tickets/687967f76c97c33526f1f80f
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "assignedTo": "agent@example.com",
  "description": "User now reports additional error"
}
